# Generated by Django 6.0.6 on 2026-06-16 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('strength', models.CharField(max_length=100)),
                ('form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('LIQUID', 'Liquid'), ('INJECTION', 'Injection'), ('INHALER', 'Inhaler')], default='TABLET', max_length=20)),
                ('is_controlled_substance', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=100)),
                ('sig', models.CharField(max_length=300)),
                ('quantity', models.PositiveIntegerField()),
                ('refills_authorized', models.PositiveIntegerField(default=0)),
                ('refills_remaining', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('DISCONTINUED', 'Discontinued')], db_index=True, default='ACTIVE', max_length=20)),
                ('date_written', models.DateField()),
                ('expiration_date', models.DateField()),
                ('pharmacy', models.CharField(blank=True, max_length=200)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinic.medication')),
                ('prescriber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinic.doctor')),
            ],
            options={
                'ordering': ['-date_written'],
            },
        ),
        migrations.CreateModel(
            name='RefillRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('NEEDS_PROVIDER_REVIEW', 'Needs provider review'), ('DENIED', 'Denied')], db_index=True, max_length=30)),
                ('decision_reason', models.CharField(blank=True, max_length=300)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refill_requests', to='clinic.prescription')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
