# Generated by Django 6.0.6 on 2026-06-16 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_medication_prescription_refillrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(blank=True, choices=[('HMO', 'HMO - Health Maintenance Organization'), ('PPO', 'PPO - Preferred Provider Organization')], help_text='Insurance plan type this rule applies to. Leave blank for an insurance-agnostic rule.', max_length=3, null=True)),
                ('fixed_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('specialty', models.ForeignKey(blank=True, help_text='Specialty this rule applies to. Leave blank for the global fallback rule.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_rules', to='clinic.medicaldepartment')),
            ],
            options={
                'ordering': ['specialty__name', 'insurance_type'],
                'constraints': [models.UniqueConstraint(fields=('insurance_type', 'specialty'), name='unique_billing_rule_scope')],
            },
        ),
    ]
