# Generated by Django 6.0.6 on 2026-06-29 23:50

import clinic.models.appointment
import clinic.models.human_escalation
import clinic.models.refill_request
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_patient_model_and_public_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='public_id',
            field=models.CharField(default=clinic.models.appointment._appointment_public_id, editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='patientinsurance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_policies', to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='clinic.patient'),
        ),
        migrations.AlterField(
            model_name='refillrequest',
            name='public_id',
            field=models.CharField(default=clinic.models.refill_request._refill_public_id, editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='HumanEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=clinic.models.human_escalation._escalation_public_id, editable=False, max_length=32, unique=True)),
                ('reported_name', models.CharField(max_length=200)),
                ('reported_phone', models.CharField(db_index=True, max_length=20)),
                ('reported_identification_number', models.CharField(db_index=True, max_length=50)),
                ('initial_intent', models.TextField()),
                ('failure_reason', models.TextField()),
                ('agent_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('RESOLVED', 'Resolved')], db_index=True, default='NEW', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalations', to='clinic.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
